// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9noGOBh8wswIr8bNk9BCNtrG0tzAHfGE',
    appId: '1:831614334735:web:2935dce24207145386707a',
    messagingSenderId: '831614334735',
    projectId: 'assou-app',
    authDomain: 'assou-app.firebaseapp.com',
    storageBucket: 'assou-app.firebasestorage.app',
    measurementId: 'G-FRWM17Y14P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgINfpsZJYYhs9LBL7HnP-HDNsQ6u8oWE',
    appId: '1:831614334735:android:ab543ca1498c639386707a',
    messagingSenderId: '831614334735',
    projectId: 'assou-app',
    storageBucket: 'assou-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNuDIkrLAtoG3IhUnHEHOL3P1FwIL1z48',
    appId: '1:831614334735:ios:4f4ee129fbe6fba486707a',
    messagingSenderId: '831614334735',
    projectId: 'assou-app',
    storageBucket: 'assou-app.firebasestorage.app',
    iosBundleId: 'com.example.projetAssouFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNuDIkrLAtoG3IhUnHEHOL3P1FwIL1z48',
    appId: '1:831614334735:ios:4f4ee129fbe6fba486707a',
    messagingSenderId: '831614334735',
    projectId: 'assou-app',
    storageBucket: 'assou-app.firebasestorage.app',
    iosBundleId: 'com.example.projetAssouFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9noGOBh8wswIr8bNk9BCNtrG0tzAHfGE',
    appId: '1:831614334735:web:750d150fc66471b986707a',
    messagingSenderId: '831614334735',
    projectId: 'assou-app',
    authDomain: 'assou-app.firebaseapp.com',
    storageBucket: 'assou-app.firebasestorage.app',
    measurementId: 'G-VGN3M4JRVH',
  );
}
